"""Fix metadata field names

Revision ID: 5a17a119abb9
Revises: 3ec78bc02d86
Create Date: 2025-09-27 06:11:04.535268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a17a119abb9'
down_revision = '3ec78bc02d86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
